version: "3"
services:
  client:
    container_name: express-react-dockerized_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_client
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      # - "API_URL: '${API_URL}:${SERVER_PORT}/api'"
      - "API_URL=http://localhost:5000/api"
  server:
    container_name: express-react-dockerized_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_server
    ports:
    - ${SERVER_PORT}:5000
    volumes:
    - ./server:/server
    - /server/node_modules
